assertEquals is clearly comparing object identities not content - changing to assertTrue requires we override equals in our test class. Giving it a try with a case class which does all that
testHdfsSystemProducerAvroWrite FAILED
    java.lang.AssertionError: expected:<org.apache.samza.system.hdfs.TestHdfsSystemProducerTestSuite$AvroTestClass@2e66dbcc> but was:<org.apache.samza.system.hdfs.TestHdfsSystemProducerTestSuite$AvroTestClass@152657a7>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:145)
        at org.apache.samza.system.hdfs.TestHdfsSystemProducerTestSuite.testHdfsSystemProducerAvroWrite(TestHdfsSystemProducerTestSuite.scala:300)