Attempt at fixing following (changed to method taking OutputStream instead of File as second parameter and using dfs to create+open stream)
java.io.FileNotFoundException: /tmp/order_and_feats_flat_avro/2016_02_11/hdfs-25a01b5c-1021-4ecf-92a6-02e49b72a6b4-00001 (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.apache.avro.file.DataFileWriter.create(DataFileWriter.java:118)
        at org.apache.samza.system.hdfs.writer.AvroDataFileHdfsWriter.getNextWriter(AvroDataFileHdfsWriter.scala:101)
        at org.apache.samza.system.hdfs.writer.AvroDataFileHdfsWriter.write(AvroDataFileHdfsWriter.scala:77)