Ok we still need a default constructor apparently
testHdfsSystemProducerWriteAvroBatches FAILED
    java.lang.RuntimeException: java.lang.NoSuchMethodException: org.apache.samza.system.hdfs.TestHdfsSystemProducerTestSuite$AvroTestClass.<init>()
        at org.apache.avro.specific.SpecificData.newInstance(SpecificData.java:266)
        at org.apache.avro.specific.SpecificData.newRecord(SpecificData.java:282)
        at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:170)
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:148)
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:139)
        at org.apache.avro.file.DataFileStream.next(DataFileStream.java:233)
        at org.apache.avro.file.DataFileStream.next(DataFileStream.java:220)
        at org.apache.samza.system.hdfs.TestHdfsSystemProducerTestSuite$$anonfun$testHdfsSystemProducerWriteAvroBatches$2.apply(TestHdfsSystemProducerTestSuite.scala:344)
        at org.apache.samza.system.hdfs.TestHdfsSystemProducerTestSuite$$anonfun$testHdfsSystemProducerWriteAvroBatches$2.apply(TestHdfsSystemProducerTestSuite.scala:339)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at org.apache.samza.system.hdfs.TestHdfsSystemProducerTestSuite.testHdfsSystemProducerWriteAvroBatches(TestHdfsSystemProducerTestSuite.scala:339)

        Caused by:
        java.lang.NoSuchMethodException: org.apache.samza.system.hdfs.TestHdfsSystemProducerTestSuite$AvroTestClass.<init>()
            at java.lang.Class.getConstructor0(Class.java:3082)
            at java.lang.Class.getDeclaredConstructor(Class.java:2178)
            at org.apache.avro.specific.SpecificData.newInstance(SpecificData.java:260)